# Site settings
title: Gokul Raghuraman's Blog
email: gokul2005@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a software/web developer with a focus in machine learning, 
  computer graphics, and computer vision.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gokulr.com" # the base hostname & protocol for your site
github_username:  gokul-raghuraman
parmalink: /blog/:categories/:year/:month/:day/:title.html
# Build settings
markdown: kramdown
